dist: trusty
language: node_js
node_js:
 - "8"
 - "10"
env:
  global:
    - CC=clang
    - CXX=clang++
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise
    packages:
      - clang
      - cmake-data
      - cmake
      - gcc-4.9
      - g++-4.9
before_install:
  # Install CMake
  - curl -sSL https://cmake.org/files/v3.5/cmake-3.5.2-Linux-x86_64.tar.gz | tar -xzC /opt
  - export PATH="/opt/cmake-3.5.2-Linux-x86_64/bin/:$PATH"
  # Install Kyoto Cabinet
  - sudo ./install-kc-ci.sh
cache:
  apt: true
  directories:
    - node_modules
sudo: required
